version: '3.2'
services:
  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    network_mode: host
    ports:
      - 8000:8080
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/jenkins_home:/var/jenkins_home
